import { IconHolder } from "@/components/our/iconHolder";
import { CommonTableHeader } from "@/utils/typeUtils.dto";
import { Box, Table } from "@mui/joy";
import { MdCheckCircle, MdRemove } from "react-icons/md";

export const membros = [
  {
    MembroID: "273482",
    Nome: "Agenor Ferronato",
    Telefone: "(54) 99974-3834",
    Celular: "(54) 99974-3834",
    Email: "agenorferronato@outlook.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "289676",
    Nome: "Alice Fiorella Suarez Cabral",
    Telefone: "",
    Celular: "5496356387",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "34",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273102",
    Nome: "Alisson Gabriel Ribeiro Matias ",
    Telefone: "(54) 99246-5225",
    Celular: "(54) 99246-5225",
    Email: "diacono.alissonmatias@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273120",
    Nome: "Ana Raquel de Carvalho",
    Telefone: "(84) 99903-1334",
    Celular: "(84) 99903-1334",
    Email: "aninha_rc@yahoo.com.br",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "Transferência",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273274",
    Nome: "André Lima Santi",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273110",
    Nome: "Andréa Kono Miyabukuro Biazus",
    Telefone: "(54) 991337308",
    Celular: "(54) 991337308",
    Email: "akmbiazus@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "289675",
    Nome: "Áquila Matias Suarez Cabral",
    Telefone: "",
    Celular: "5496356387",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "274116",
    Nome: "Benjamin Begrow Rech",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "274117",
    Nome: "Betânia Begrow Rech",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273273",
    Nome: "Bruna Giacomini Lima Santi",
    Telefone: "(54) 99165-0984",
    Celular: "(55) 98404-2627 (whats)",
    Email: "brunagiacominilima@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273270",
    Nome: "Caio Vinicius Alves Ferreira ",
    Telefone: "(54) 99606-1288",
    Celular: "(54) 99606-1288",
    Email: "caioviniciusaferreira@gmail.com",
    Membro: "Comungante",
    Oficial: "Presbítero em disponibilidade",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "276960",
    Nome: "Carlos Augusto Midon Zacarias",
    Telefone: "(55) 984446454",
    Celular: "(55) 984446454",
    Email: "midon_1982@yahooo.com.br",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "281",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "272613",
    Nome: "Cecilia Calgaro Vargas",
    Telefone: "54991156533",
    Celular: "54984041472",
    Email: "mssvargas07@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273118",
    Nome: "Clarice dos Santos Erves ",
    Telefone: "54999253988",
    Celular: "54999253988",
    Email: "joaoerves@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "274115",
    Nome: "Clarissa De Vit Begrow Rech",
    Telefone: "(54) 98402-3826",
    Celular: "(54) 98402-3826",
    Email: "claridv.beg@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "289286",
    Nome: "Cláudia Vanessa Simón Suaréz Cabral",
    Telefone: "(54) 999048894",
    Celular: "(54) 999048894",
    Email: "claudinhavssc@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "34",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "289285",
    Nome: "Cristiano Stecanella Cabral",
    Telefone: "(54) 996356387",
    Celular: "(54) 996356387",
    Email: "cristiano_cabral314@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "34",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "274114",
    Nome: "Denis Esmael Pradella Rech",
    Telefone: "(54) 98402-3826",
    Celular: "(54) 98402-3826",
    Email: "denisrech@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273104",
    Nome: "Denise Silva ",
    Telefone: "(54) 99621-4075",
    Celular: "(54) 99621-4075",
    Email: "desilva.db@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273269",
    Nome: "Diequison de Almeida Antunes ",
    Telefone: "(54) 99200-0667",
    Celular: "(54) 99200-0667",
    Email: "diequisonantunes@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273512",
    Nome: "Domênica Reis Drosdowski ",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273128",
    Nome: "Eduardo Miyabukuro Biazus",
    Telefone: "(54) 991337308",
    Celular: "(54) 991337308",
    Email: "akmbiazus@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "64",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273117",
    Nome: "Elisa dos Santos Erves",
    Telefone: "54999253988",
    Celular: "54999253988",
    Email: "joaoerves@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273895",
    Nome: "Elisa Lima de Carvalho ",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "279917",
    Nome: "Elizabeth Cristina do Nascimento Ribeiro",
    Telefone: "(54) 99241-1623",
    Celular: "(54) 99241-1623",
    Email: "elizabeth.16cristina@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "232",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273114",
    Nome: "Eloísa Guimarães Garcia Maier dos Santos - 27/04/2020",
    Telefone: "+5554996209691",
    Celular: "+5554996209691",
    Email: "maier_gui_11@hotmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273381",
    Nome: "Emilene Cordeiro dos Santos Barbosa",
    Telefone: "(54) 98139-7253",
    Celular: "(54) 98139-7253",
    Email: "emilenebarb@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273127",
    Nome: "Felipe Miyabukuro Biazus",
    Telefone: "(54) 991041756",
    Celular: "(54) 991041756",
    Email: "felipebiazus08@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273291",
    Nome: "Gelson Oliveira",
    Telefone: "(54) 99113-6088",
    Celular: "(54) 99113-6088",
    Email: "",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273783",
    Nome: "Gerson Assis Rodrigues",
    Telefone: "(54) 99659-3745",
    Celular: "(54) 99659-3745",
    Email: "gersonjc13j@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "279916",
    Nome: "Glaubson Wesllen Corrêa Ribeiro",
    Telefone: "(54) 98129-0022",
    Celular: "(54) 98129-0022",
    Email: "glaubsonribeiro.brf@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "232",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273100",
    Nome: "Guilherme Maier dos Santos Guimarães Garcia",
    Telefone: "+5554991872013",
    Celular: "+5554991872013",
    Email: "maier_gui_11@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273115",
    Nome: "Helena Guimarães Garcia Maier dos Santos - 15/07/2022",
    Telefone: "+5554991872013",
    Celular: "+5554991872013",
    Email: "maier_gui_11@hotmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "280223",
    Nome: "Inez Boff Mazzochi",
    Telefone: "",
    Celular: "54081038210",
    Email: "",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "224",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "279918",
    Nome: "Isadora Catarina do Nascimento Ribeiro",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "232",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273480",
    Nome: "Ivanilde Tronco Ferronato",
    Telefone: "(54) 98416-8395",
    Celular: "(54) 98416-8395",
    Email: "",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273406",
    Nome: "Ivonete Rodrigues Tavares Alves",
    Telefone: "(54) 98152-5364",
    Celular: "(54) 98152-5364",
    Email: "ivonetealves1980@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273103",
    Nome: "Jackson Pereira de Lima",
    Telefone: "(84) 987653133",
    Celular: "(84) 987653133",
    Email: "pereiradelimajackson@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "330",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273121",
    Nome: "Jean Carlos da Silva Sampaio",
    Telefone: "54999708141",
    Celular: "",
    Email: "katlineveline@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273109",
    Nome: "Jean Carlos da Silva Sampaio Junior ",
    Telefone: "54999381276",
    Celular: "54999381276",
    Email: "jean27junior05@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "90",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "275022",
    Nome: "Jenifer Quintanhia Raimondi",
    Telefone: "(54) 99158-8099",
    Celular: "(54) 99158-8099",
    Email: "jeniferramondi@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "311",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273101",
    Nome: "João Paulo Pagno Erves ",
    Telefone: "54999253988",
    Celular: "54999253988",
    Email: "joaoerves@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "275729",
    Nome: "João Torquatro Alves de Freitas",
    Telefone: "",
    Celular: "6399236-4994",
    Email: "jtjtaf@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "176",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273113",
    Nome: "Joice Ferreira Mariano Rodrigues ",
    Telefone: "(54) 991642213",
    Celular: "(54) 991642213",
    Email: "joice.fm.rodrigues@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273271",
    Nome: "Kaline de Aquino Feliciano Ferreira ",
    Telefone: "(54) 99680-9949",
    Celular: "(54) 99680-9949",
    Email: "kalineaquinof@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "279325",
    Nome: "Katherine Noemi Yanez Maray",
    Telefone: "(54) 99365-5402",
    Celular: "(54) 99365-5402",
    Email: "",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "239",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273107",
    Nome: "Katlin Eveline de Castro ",
    Telefone: "54999708141",
    Celular: "54999708141",
    Email: "katlineveline@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "90",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273391",
    Nome: "Kevinei Mayana de Mattos de Oliveira da Silva",
    Telefone: "(54) 98112-2577",
    Celular: "(54) 98112-2577",
    Email: "",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273408",
    Nome: "Laura Rodrigues da Silva",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273390",
    Nome: "Leonardo Maciel da Silva",
    Telefone: "(54) 98130-5983",
    Celular: "(54) 98130-5983",
    Email: "macielleonardo269@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273126",
    Nome: "Letícia de Oliveira dos Santos Erves ",
    Telefone: "54999253988",
    Celular: "54991940863",
    Email: "leticiaerves@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273407",
    Nome: "Lorenzo Rodrigues da Silva",
    Telefone: "(54) 98123-5164",
    Celular: "(54) 98123-5164",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "274170",
    Nome: "Lucilene Mendes Muricy Matias",
    Telefone: "",
    Celular: "41 9 9177-0246",
    Email: "lucilene.muricy@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "325",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "275730",
    Nome: "Maria Alves Ferreira de Freitas ",
    Telefone: "",
    Celular: "63984020628",
    Email: "mariaffneta@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "299",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "276961",
    Nome: "Marla Saionara Fernandez Ribeiro Zacarias",
    Telefone: "",
    Celular: "(54) 9 8416-4464 ",
    Email: "",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "281",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "272611",
    Nome: "Marlon Santana da Silva Vargas",
    Telefone: "54991156533",
    Celular: "54991156533",
    Email: "mssvargas07@gmail.com",
    Membro: "Comungante",
    Oficial: "Presbítero",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273392",
    Nome: "Mateus de Mattos da Silva",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273272",
    Nome: "Matheus Ribeiro Santi",
    Telefone: "(55) 99188-0770",
    Celular: "(55) 99188-0770",
    Email: "matheusrsanti@gmail.com",
    Membro: "Comungante",
    Oficial: "Diácono",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273275",
    Nome: "Mário Júnior Dela Pase",
    Telefone: "(54) 99223-2076",
    Celular: "(54) 99223-2076",
    Email: "delapasejunior2@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273278",
    Nome: "Miguel Kovaleski Dela Pase",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273280",
    Nome: "Neusa Palhano de Oliveira",
    Telefone: "",
    Celular: "",
    Email: "neusapalhanooliveira",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273389",
    Nome: "Nickolas Borges Ruppenthal",
    Telefone: "(54) 99180-7117",
    Celular: "(54) 99180-7117",
    Email: "nick.ruppentha@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273797",
    Nome: "Noah de Aquino Ferreira",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273404",
    Nome: "Paulo Cesar Alves da Silva",
    Telefone: "(54) 99909-0208",
    Celular: "(54) 99909-0208",
    Email: "paulo.ipb2017@gmail.com",
    Membro: "Comungante",
    Oficial: "Presbítero",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273276",
    Nome: "Pâmela Kovaleski Dela Pase",
    Telefone: "(54) 98436-4373",
    Celular: "(54) 98436-4373",
    Email: "kovaleskipamela2@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "279324",
    Nome: "Pedro Jose Castillo Herrade",
    Telefone: "(54) 99916-2636",
    Celular: "(54) 99916-2636",
    Email: "",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273277",
    Nome: "Pietra Kovaleski Dela Pase",
    Telefone: "",
    Celular: "",
    Email: "",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "272612",
    Nome: "Priscila Silveira Calgaro Vargas",
    Telefone: "54984041472",
    Celular: "54984041472",
    Email: "priscvargas@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273510",
    Nome: "Rafael Drosdowski Padilha",
    Telefone: "(54) 99673-4608",
    Celular: "(54) 99673-4608",
    Email: "rafiudsdrosdowski@gmail.com",
    Membro: "Comungante",
    Oficial: "Diácono",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273125",
    Nome: "Rafaela Guimarães Garcia Maier dos Santos ",
    Telefone: "+5554996209691",
    Celular: "+5554996209691",
    Email: "rafa_ggarcia@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273111",
    Nome: "Rejane Cardoso de Oliveira do Nascimento ",
    Telefone: "(54) 991530551",
    Celular: "(54) 991530551",
    Email: "rj1nascimento@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273106",
    Nome: "Ronaldo Duarte da Silva ",
    Telefone: "(54) 98112-5928",
    Celular: "(54) 98112-5928",
    Email: "bigutho3@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273264",
    Nome: "Rosangela Huff",
    Telefone: "(54) 99128-3557",
    Celular: "(54) 99128-3557",
    Email: "rosan.preta@hotmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "327",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273268",
    Nome: "Sara Bruing dos Santos Antunes ",
    Telefone: "(54) 98447-4388",
    Celular: "(54) 98447-4388",
    Email: "sarabruing63@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273260",
    Nome: "Selma Rodrigues Silva Szczypula",
    Telefone: "(54) 999305925",
    Celular: "(54) 999305925",
    Email: "",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "22",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273289",
    Nome: "Taisilene Cordeiro Furtado Carballo",
    Telefone: "(54) 99936-7935",
    Celular: "(54) 99936-7935",
    Email: "taisilenefurtado@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273511",
    Nome: "Tamires Reis Drosdowski",
    Telefone: "(54) 99212-9429",
    Celular: "(54) 99212-9429",
    Email: "tamiresreistr.18@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "272614",
    Nome: "Valentin Calgaro Vargas",
    Telefone: "54991156533",
    Celular: "54984041472",
    Email: "mssvargas07@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273288",
    Nome: "Vilmar Hugo Salvi Carballo",
    Telefone: "(54) 99934-8282",
    Celular: "(54) 99934-8282",
    Email: "hugo_carballo@hotmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "15",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273509",
    Nome: "Vinícius Alberto Biazus",
    Telefone: "(54) 99195-2214",
    Celular: "(54) 99195-2214",
    Email: "vabiazus@gmail.com",
    Membro: "Não membro",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273279",
    Nome: "Vitor Lazzaron",
    Telefone: "(54) 99633-6102",
    Celular: "(54) 99633-6102",
    Email: "vitorlazzaron20@gmail.com",
    Membro: "Comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
  {
    MembroID: "273124",
    Nome: "Zayon Rodrigues",
    Telefone: "(54) 99164-2213",
    Celular: "(54) 99164-2213",
    Email: "joice.fm.rodrigues@gmail.com",
    Membro: "Não comungante",
    Oficial: "Não oficial",
    Diferenca: "332",
    IgrejaNome: "Igreja Presbiteriana de Caxias do Sul",
    Situa: "Ativo",
    MeioDemissao: "",
    Situacao: "<center><img src='imagens/ok1.png'></center>",
  },
];

export interface ICalvinusMember {
  MembroID: number;
  Nome: string;
  Telefone: string;
  Celular: string;
  Email: string;
  Membro: string;
  Oficial: string;
  Diferenca: number;
  IgrejaNome: string;
  Situa: string;
  MeioDemissao: string;
}

export const iCalvinusMemberHeaders: CommonTableHeader<
  ICalvinusMember,
  | "MembroID"
  | "Nome"
  | "Telefone"
  | "Celular"
  | "Email"
  | "Membro"
  | "Oficial"
  | "IgrejaNome"
  | "Situa"
>[] = [
  {
    id: "MembroID",
    headerName: "ID",
    align: "right",
    width: "75px",
  },
  {
    id: "Nome",
    headerName: "Nome",
  },
  {
    id: "Email",
    headerName: "Email",
  },
  {
    id: "Telefone",
    headerName: "Telefone",
    width: "150px",
    align: "right",
  },
  {
    id: "Celular",
    headerName: "Celular",
    width: "150px",
    align: "right",
  },
  {
    id: "Membro",
    headerName: "Membro",
    width: "150px",
  },
  {
    id: "Situa",
    headerName: "",
    align: "center",
    width: "50px",
  },
];

function Form() {
  return (
    <Box
      display={"flex"}
      flexDirection={{ xs: "column", md: "row" }}
      justifyContent={"center"}
      alignItems={"center"}
      height={"100%"}
      gap={2}
    >
      <Table sx={{ tableLayout: "fixed" }}>
        <thead>
          <tr>
            {iCalvinusMemberHeaders.map((c) => (
              <th
                key={c.id}
                align={c.headerAlign || "left"}
                style={{
                  width: c.width || "auto",
                  textAlign: c.headerAlign || "left",
                }}
              >
                {c.headerName}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {membros.map((membro) => (
            <tr key={membro.MembroID}>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "MembroID")
                    ?.align || "left"
                }
              >
                {membro.MembroID || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Nome")?.align ||
                  "left"
                }
              >
                {membro.Nome || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Email")?.align ||
                  "left"
                }
              >
                {membro.Email || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Telefone")
                    ?.align || "left"
                }
              >
                {membro.Telefone || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Celular")
                    ?.align || "left"
                }
              >
                {membro.Celular || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Membro")
                    ?.align || "left"
                }
              >
                {membro.Membro || (
                  <IconHolder size="sm" color="neutral">
                    <MdRemove />
                  </IconHolder>
                )}
              </td>
              <td
                align={
                  iCalvinusMemberHeaders.find((c) => c.id === "Situa")?.align ||
                  "left"
                }
              >
                <IconHolder
                  size="sm"
                  color={membro.Situa === "Ativo" ? "success" : "danger"}
                >
                  <MdCheckCircle />
                </IconHolder>
              </td>
            </tr>
          ))}
        </tbody>
      </Table>
    </Box>
  );
}

export default Form;
